#es用户名 密码等配置
elasticsearch:
  host: ${eshost:127.0.0.1}
  username: ${esusername:admin}
  password: ${espassword:admin}
  port: ${esport:9200}
  #deploy dev
  isDev: ${isDev:false}

#网站埋点数据库
tracker:
  host: ${teshost:127.0.0.1}
  username: ${tesusername:admin}
  password: ${tespassword:admin}
  port: ${tesport:9200}


kafka:
  need: ${kneed:false}
  bootstrap: ${kbootstrap:127.0.0.1:9092}
  producer:
  consumer:
    group: ${kgroup:openeuler}


#定时读取配置
scheduled:
  cron: 0 31 11 ? * *

#openEuler    openGauss    openLookeng    mindSpore
system: ${searchsystem:openEuler}


#formal test
dep: ${depp:test}

#异步配置
asyncThreadPool:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 10
  keepAliveSeconds: 300
  awaitTerminationSeconds: 300
  threadNamePrefix: thread-name-prefix

server:
  port: 8080